# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='/profile/photo')),
                ('tipo', models.CharField(blank=True, choices=[('EM', 'Empresa'), ('EG', 'Egresado')], default='EG', max_length=1, null=True)),
            ],
        ),
    ]
