# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('EM', 'Empresa'), ('EG', 'Egresado')], default='EG', max_length=2, null=True),
        ),
    ]
