# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161125_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='/accounts/photo'),
        ),
    ]
