# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161128_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
