# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('egresados', '0003_auto_20161128_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudio',
            old_name='id_egresado',
            new_name='egresado',
        ),
        migrations.AddField(
            model_name='egresado',
            name='egr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
