# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('egresados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_siglas', models.CharField(blank=True, max_length=10, null=True)),
                ('cam_repnombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_repcargo', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_repperiodo', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_calleynum', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_cp', models.CharField(blank=True, max_length=5, null=True)),
                ('cam_telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('cam_paginaweb', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_cargocontacto', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_telcontacto', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_email', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_fecha_registro', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_validada', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_nombre_completo', models.CharField(blank=True, max_length=150, null=True)),
                ('emp_calle', models.CharField(blank=True, max_length=150, null=True)),
                ('emp_colonia', models.CharField(blank=True, max_length=150, null=True)),
                ('emp_municipio', models.CharField(blank=True, choices=[('Alan', 'Acatlán'), ('Alan', 'Acaxochitlán'), ('Apan', 'Actopan'), ('Aide', 'Agua Blanca de Iturbide'), ('Auba', 'Ajacuba'), ('Acan', 'Alfajayucan'), ('Aoya', 'Almoloya'), ('Apan', 'Apan'), ('Auia', 'Atitalaquia'), ('Axco', 'Atlapexco'), ('Aula', 'Atotonilco de Tula'), ('Ande', 'Atotonilco el Grande'), ('Cali', 'Calnali'), ('Cnal', 'Cardonal'), ('Cngo', 'Chapantongo'), ('Ccan', 'Chapulhuacán'), ('Ctla', 'Chilcuautla'), ('Cosa', 'Cuautepec de Hinojosa'), ('Enal', 'El Arenal'), ('Elan', 'Eloxochitlán'), ('Eata', 'Emiliano Zapata'), ('Ecan', 'Epazoyucan'), ('Fero', 'Francisco I. Madero'), ('Hmpo', 'Huasca de Ocampo'), ('Htla', 'Huautla'), ('Hngo', 'Huazalingo'), ('Htla', 'Huehuetla'), ('Hyes', 'Huejutla de Reyes'), ('Hpan', 'Huichapan'), ('Ipan', 'Ixmiquilpan'), ('Jzma', 'Jacala de Ledezma'), ('Jcan', 'Jaltocán'), ('Jlgo', 'Juárez Hidalgo'), ('Lian', 'La Misión'), ('Ltla', 'Lolotla'), ('Mpec', 'Metepec'), ('Mlan', 'Metztitlán'), ('Mrma', 'Mineral de la Reforma'), ('Mico', 'Mineral del Chico'), ('Mnte', 'Mineral del Monte'), ('Mrez', 'Mixquiahuala de Juárez'), ('Mlla', 'Molango de Escamilla'), ('Nres', 'Nicolás Flores'), ('Nran', 'Nopala de Villagrán'), ('Orez', 'Omitlán de Juárez'), ('Poto', 'Pachuca de Soto'), ('Pula', 'Pacula'), ('Pres', 'Pisaflores'), ('Pgan', 'Progreso de Obregón'), ('Slan', 'San Agustín Metzquititlán'), ('Saca', 'San Agustín Tlaxiaca'), ('Spec', 'San Bartolo Tutotepec'), ('Slan', 'San Felipe Orizatlán'), ('Sdor', 'San Salvador'), ('Saya', 'Santiago de Anaya'), ('Srre', 'Santiago Tulantepec de Lugo Guerre'), ('Scan', 'Singuilucan'), ('Tllo', 'Tasquillo'), ('Ttla', 'Tecozautla'), ('Tria', 'Tenango de Doria'), ('Tlco', 'Tepeapulco'), ('Tero', 'Tepehuacán de Guerrero'), ('Tmpo', 'Tepeji del Río de Ocampo'), ('Tlan', 'Tepetitlán'), ('Tngo', 'Tetepango'), ('Tama', 'Tezontepec de Aldama'), ('Tngo', 'Tianguistengo'), ('Tuca', 'Tizayuca'), ('Tpan', 'Tlahuelilpan'), ('Tepa', 'Tlahuiltepa'), ('Tapa', 'Tlanalapa'), ('Tnol', 'Tlanchinol'), ('Tpan', 'Tlaxcoapan'), ('Tuca', 'Tolcayuca'), ('Tnde', 'Tula de Allende'), ('Tavo', 'Tulancingo de Bravo'), ('Vpec', 'Villa de Tezontepec'), ('Xpan', 'Xochiatipan'), ('Xlan', 'Xochicoatlán'), ('Yica', 'Yahualica'), ('Zles', 'Zacualtipán de ?ngeles'), ('Zrez', 'Zapotlán de Juárez'), ('Zala', 'Zempoala'), ('Zana', 'Zimapán')], max_length=4, null=True)),
                ('emp_cp', models.CharField(blank=True, max_length=5, null=True)),
                ('emp_direccionvisitas', models.CharField(blank=True, max_length=150, null=True)),
                ('emp_tel', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_fax', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emp_replegal', models.CharField(blank=True, max_length=40, null=True)),
                ('emp_start_date', models.DateField(blank=True, null=True)),
                ('emp_total_number_workes', models.IntegerField(blank=True, null=True)),
                ('emp_giro', models.CharField(blank=True, max_length=40, null=True)),
                ('emp_registry_date', models.DateField(blank=True, null=True)),
                ('emp_name_project_manager', models.CharField(blank=True, max_length=60, null=True)),
                ('emp_puesto', models.CharField(blank=True, max_length=60, null=True)),
                ('emp_rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_acteconomica', models.CharField(blank=True, max_length=250, null=True)),
                ('emp_products_services', models.TextField(blank=True, null=True)),
                ('emp_name_project', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_description', models.TextField(blank=True, null=True)),
                ('emp_size', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_clasificacion', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_sectores', models.IntegerField(blank=True, null=True)),
                ('emp_sector', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_rango_trab', models.CharField(blank=True, max_length=60, null=True)),
                ('emp_acceso', models.CharField(blank=True, max_length=60, null=True)),
                ('emp_extension', models.CharField(blank=True, max_length=60, null=True)),
                ('emp_rfc_imagen', models.ImageField(blank=True, null=True, upload_to='rfc_imagen')),
                ('emp_identificacion', models.CharField(blank=True, max_length=60, null=True)),
                ('emp_identificacion_tutor', models.CharField(blank=True, max_length=60, null=True)),
                ('emp_comprobante', models.CharField(blank=True, max_length=60, null=True)),
                ('emp_carta', models.CharField(blank=True, max_length=60, null=True)),
                ('emp_pagina', models.CharField(blank=True, max_length=60, null=True)),
                ('emp_ubucacion', models.TextField(blank=True, null=True)),
                ('emp_croquis', models.CharField(blank=True, max_length=60, null=True)),
                ('emp_emailreproy', models.EmailField(blank=True, max_length=254, null=True)),
                ('emp_validada', models.IntegerField(blank=True, null=True)),
                ('emp_etapa', models.CharField(blank=True, max_length=60, null=True)),
                ('emp_carpeta', models.IntegerField(blank=True, null=True)),
                ('emp_administra', models.IntegerField(blank=True, null=True)),
                ('emp_visto', models.IntegerField(blank=True, null=True)),
                ('emp', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='accounts.Profile')),
                ('emp_camara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camara', to='empresas.Camara')),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto_solicitante', models.CharField(max_length=80)),
                ('activades', models.TextField()),
                ('dias', models.TextField()),
                ('horario_entrada', models.TimeField(blank=True, null=True)),
                ('horario_entrada_sabado', models.TimeField(blank=True, null=True)),
                ('horario_salida', models.TimeField(blank=True, null=True)),
                ('horario_salida_sabado', models.TimeField(blank=True, null=True)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('fecha_asignado', models.DateField(blank=True, null=True)),
                ('vacante_activa', models.BooleanField(default=True)),
                ('id_egresado', models.ManyToManyField(blank=True, null=True, related_name='vacante', to='egresados.Egresado')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacante', to='empresas.Empresa')),
            ],
        ),
    ]
