# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='id_egresado',
            field=models.ManyToManyField(blank=True, related_name='vacante', to='egresados.Egresado'),
        ),
    ]
