# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='emp_municipio',
            field=models.CharField(blank=True, choices=[('Alan', 'Acatlán'), ('Alan', 'Acaxochitlán'), ('Apan', 'Actopan'), ('Aide', 'Agua Blanca de Iturbide'), ('Auba', 'Ajacuba'), ('Acan', 'Alfajayucan'), ('Aoya', 'Almoloya'), ('Apan', 'Apan'), ('Auia', 'Atitalaquia'), ('Axco', 'Atlapexco'), ('Aula', 'Atotonilco de Tula'), ('Ande', 'Atotonilco el Grande'), ('Cali', 'Calnali'), ('Cnal', 'Cardonal'), ('Cngo', 'Chapantongo'), ('Ccan', 'Chapulhuacán'), ('Ctla', 'Chilcuautla'), ('Cosa', 'Cuautepec de Hinojosa'), ('Enal', 'El Arenal'), ('Elan', 'Eloxochitlán'), ('Eata', 'Emiliano Zapata'), ('Ecan', 'Epazoyucan'), ('Fero', 'Francisco I. Madero'), ('Hmpo', 'Huasca de Ocampo'), ('Htla', 'Huautla'), ('Hngo', 'Huazalingo'), ('Htla', 'Huehuetla'), ('Hyes', 'Huejutla de Reyes'), ('Hpan', 'Huichapan'), ('Ipan', 'Ixmiquilpan'), ('Jzma', 'Jacala de Ledezma'), ('Jcan', 'Jaltocán'), ('Jlgo', 'Juárez Hidalgo'), ('Lian', 'La Misión'), ('Ltla', 'Lolotla'), ('Mpec', 'Metepec'), ('Mlan', 'Metztitlán'), ('Mrma', 'Mineral de la Reforma'), ('Mico', 'Mineral del Chico'), ('Mnte', 'Mineral del Monte'), ('Mrez', 'Mixquiahuala de Juárez'), ('Mlla', 'Molango de Escamilla'), ('Nres', 'Nicolás Flores'), ('Nran', 'Nopala de Villagrán'), ('Orez', 'Omitlán de Juárez'), ('Poto', 'Pachuca de Soto'), ('Pula', 'Pacula'), ('Pres', 'Pisaflores'), ('Pgan', 'Progreso de Obregón'), ('Slan', 'San Agustín Metzquititlán'), ('Saca', 'San Agustín Tlaxiaca'), ('Spec', 'San Bartolo Tutotepec'), ('Slan', 'San Felipe Orizatlán'), ('Sdor', 'San Salvador'), ('Saya', 'Santiago de Anaya'), ('Srre', 'Santiago Tulantepec de Lugo Guerre'), ('Scan', 'Singuilucan'), ('Tllo', 'Tasquillo'), ('Ttla', 'Tecozautla'), ('Tria', 'Tenango de Doria'), ('Tlco', 'Tepeapulco'), ('Tero', 'Tepehuacán de Guerrero'), ('Tmpo', 'Tepeji del Río de Ocampo'), ('Tlan', 'Tepetitlán'), ('Tngo', 'Tetepango'), ('Tama', 'Tezontepec de Aldama'), ('Tngo', 'Tianguistengo'), ('Tuca', 'Tizayuca'), ('Tpan', 'Tlahuelilpan'), ('Tepa', 'Tlahuiltepa'), ('Tapa', 'Tlanalapa'), ('Tnol', 'Tlanchinol'), ('Tpan', 'Tlaxcoapan'), ('Tuca', 'Tolcayuca'), ('Tnde', 'Tula de Allende'), ('Tavo', 'Tulancingo de Bravo'), ('Vpec', 'Villa de Tezontepec'), ('Xpan', 'Xochiatipan'), ('Xlan', 'Xochicoatlán'), ('Yica', 'Yahualica'), ('Zles', 'Zacualtipán de ?ngeles'), ('Zrez', 'Zapotlán de Juárez'), ('Zala', 'Zempoala'), ('Zana', 'Zimapán')], max_length=4, null=True),
        ),
    ]
