# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20161125_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_siglas', models.CharField(blank=True, max_length=10, null=True)),
                ('cam_repnombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_repcargo', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_repperiodo', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_calleynum', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_cp', models.CharField(blank=True, max_length=5, null=True)),
                ('cam_telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('cam_paginaweb', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_cargocontacto', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_telcontacto', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_email', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_fecha_registro', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_validada', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='emp_camara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camara', to='empresas.Camara'),
        ),
    ]
