# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20161128_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='activades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='dias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
