# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20161128_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='emp_carta',
            field=models.FileField(blank=True, null=True, upload_to='empresa/carta'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='emp_comprobante',
            field=models.FileField(blank=True, null=True, upload_to='empresa/comprobante'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='emp_identificacion',
            field=models.FileField(blank=True, null=True, upload_to='empresa/ide'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='emp_identificacion_tutor',
            field=models.FileField(blank=True, null=True, upload_to='empresa/idtutor'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='emp_rfc_imagen',
            field=models.FileField(blank=True, null=True, upload_to='empresa/rfc'),
        ),
    ]
