# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_auto_20161128_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='emp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='id_egresado',
            field=models.ManyToManyField(blank=True, related_name='vacante', to=settings.AUTH_USER_MODEL),
        ),
    ]
