# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_auto_20161128_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacante',
            old_name='id_egresado',
            new_name='egresado',
        ),
        migrations.RenameField(
            model_name='vacante',
            old_name='id_empresa',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='vacante',
            old_name='puesto_solicitante',
            new_name='puesto',
        ),
    ]
